[Files]
Na=/Users/rogerfearick/Desktop/research/neutrons/All raw data and analyses from iTL neutrons 2009/100MeV/NE213/NE213_032.lst
Cs=/Users/rogerfearick/Desktop/research/neutrons/All raw data and analyses from iTL neutrons 2009/100MeV/NE213/NE213_034.lst
AmBe=/Users/rogerfearick/Desktop/research/neutrons/All raw data and analyses from iTL neutrons 2009/100MeV/NE213/NE213_035.lst
TAC=/Users/rogerfearick/Desktop/research/neutrons/All raw data and analyses from iTL neutrons 2009/100MeV/NE213/NE213_037.lst
NE213=/Users/rogerfearick/Desktop/research/neutrons/All raw data and analyses from iTL neutrons 2009/100MeV/NE213/NE213_025.lst
FC=/Users/rogerfearick/Desktop/research/neutrons/All raw data and analyses from iTL neutrons 2009/100MeV/FC/FC_035.lst

